[pytest]
pythonpath = src
asyncio_mode = auto
filterwarnings =
	default
	ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning:discord\.ext\.commands\.core
	ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning:discord\.client
	ignore:.*_UnionGenericAlias.*:DeprecationWarning:google\.genai\.types
